Prevent tmt scripts from running outside of test context
Now when scripts are moved, they are not ready to be executed anywhere
but in `execute`. Adding a short check to prevent them being used in
`prepare` or `finish`. I expected that will change gradually, e.g. there
is no reason to not use `tmt-abort` in `prepare` scripts, for example,
except its connection to `execute.

Part of the effort to implement #902.

diff --git a/tmt/steps/scripts/tmt-abort b/tmt/steps/scripts/tmt-abort
--- a/tmt/steps/scripts/tmt-abort
+++ b/tmt/steps/scripts/tmt-abort
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+if [ -z "$TMT_TEST_PIDFILE" ]; then
+    echo "tmt-abort can be used only in the context of a running test."
+    exit 1
+fi
+
 # Create the abort file.
 touch "$TMT_TEST_DATA/abort"
 # Kill PPID to exit test execution.
